export default [
    {
        id: "1",
        name: "dashboard",
        level: "1",
        path: "/dashboard",
        sort: "999",
        meta: {
            key: "dashboard",
            title: "首页",
            icon: "&#xe63b;",
            isMenuShow: true,
            isBlank: false,
        },
        layout: "default",
        children: [],
    },
    {
        id: "2",
        name: "workOrder",
        level: "1",
        path: "/workOrder",
        sort: "999",
        meta: {
            key: "workOrder",
            title: "工单中心",
            icon: "&#xe605;",
            isMenuShow: true,
            isBlank: false,
        },
        layout: "default",
        children: [
            {
                id: "2-1",
                name: "statistics",
                level: "2",
                path: "/workOrder/statistics",
                sort: "999",
                meta: {
                    key: "statistics",
                    title: "统计",
                    icon: "",
                    isMenuShow: true,
                    isBlank: false,
                },
                layout: "default",
                children: [],
            },
            {
                id: "2-2",
                name: "orderSearching",
                level: "2",
                path: "/workOrder/orderSearching",
                sort: "999",
                meta: {
                    key: "orderSearching",
                    title: "工单查询",
                    icon: "",
                    isMenuShow: true,
                    isBlank: false,
                },
                layout: "default",
                children: [
                    {
                        id: "2-2-1",
                        name: "customSearching",
                        level: "2",
                        path: "/workOrder/orderSearching/customSearching",
                        sort: "999",
                        meta: {
                            key: "customSearching",
                            title: "自定义查询",
                            icon: "",
                            isMenuShow: true,
                            isBlank: false,
                        },
                        layout: "default",
                        children: [],
                    },
                ],
            },
        ],
    },
    {
        id: "3",
        name: "CRM",
        level: "1",
        path: "",
        sort: "999",
        meta: {
            key: "CRM",
            title: "CRM",
            icon: "&#xe888;",
            isMenuShow: true,
            isBlank: false,
        },
        layout: "default",
        children: [
            {
                id: "3-1",
                name: "customer",
                level: "2",
                path: "/CRM/customer",
                sort: "999",
                meta: {
                    key: "customer",
                    title: "客户中心",
                    icon: "",
                    isMenuShow: true,
                    isBlank: false,
                },
                layout: "default",
                children: [
                    {
                        id: "3-1-1",
                        name: "firstConsultCustom",
                        level: "3",
                        path: "/CRM/customer/firstConsultCustom",
                        sort: "999",
                        meta: {
                            key: "firstConsultCustom",
                            title: "首咨客户",
                            icon: "",
                            isMenuShow: false,
                            isBlank: false,
                        },
                        layout: "default",
                        children: [],
                    },
                    {
                        id: "3-1-2",
                        name: "toBeDistributedCustom",
                        level: "3",
                        path: "/CRM/customer/toBeDistributedCustom",
                        sort: "999",
                        meta: {
                            key: "toBeDistributedCustom",
                            title: "待分配客户",
                            icon: "",
                            isMenuShow: false,
                            isBlank: false,
                        },
                        layout: "default",
                        children: [],
                    },
                ],
            },
            {
                id: "10",
                name: "album",
                level: "2",
                path: "/goods/album",
                sort: "999",
                meta: {
                    key: "goods",
                    title: "商品专辑",
                    icon: "",
                    isMenuShow: true,
                    isBlank: false,
                },
                layout: "default",
                children: [
                    {
                        id: "1001",
                        name: "albumDetails",
                        level: "3",
                        path: "/goods/album/albumDetails/:id",
                        sort: "999",
                        meta: {
                            key: "album",
                            title: "专辑详情",
                            icon: "",
                            isMenuShow: false,
                            isBlank: false,
                        },
                        layout: "default",
                        children: [],
                    },
                ],
            },
        ],
    },
    {
        id: "4",
        name: "management",
        level: "1",
        path: "",
        sort: "999",
        meta: {
            key: "management",
            title: "管理中心",
            icon: "&#xe7f1;",
            isMenuShow: true,
            isBlank: false,
        },
        layout: "default",
        children: [
            {
                id: "4-1",
                name: "customerService",
                level: "2",
                path: "/management/customerService",
                sort: "999",
                meta: {
                    key: "customerService",
                    title: "客服管理",
                    icon: "",
                    isMenuShow: true,
                    isBlank: false,
                },
                layout: "default",
                children: [
                    {
                        id: "4-1-1",
                        name: "list",
                        level: "3",
                        path: "/management/customerService/CSList",
                        sort: "999",
                        meta: {
                            key: "CSList",
                            title: "客服列表",
                            icon: "",
                            isMenuShow: false,
                            isBlank: false,
                        },
                        layout: "default",
                        children: [],
                    },
                ],
            },
        ],
    },
];
