// tip：name的命名与文件命名保持一致
export default [
    {
        id: "1",
        name: "dashboard",
        level: "1",
        path: "/dashboard",
        sort: "999",
        meta: {
            key: "dashboard",
            title: "首页",
            icon: "&#xe858;",
            isMenuShow: true,
            isBlank: false,
            isRegister: true,
        },
        layout: "default",
        children: [],
    },
    {
        id: "2",
        name: "workOrder",
        level: "1",
        path: "/workOrder",
        redirect: "/workOrder/statistics/overview",
        sort: "999",
        meta: {
            key: "workOrder",
            title: "工单中心",
            icon: "&#xe84b;",
            isMenuShow: true,
            isBlank: false,
            isRegister: true,
        },
        layout: "default",
        children: [
            {
                id: "2-1",
                name: "statistics",
                level: "2",
                path: "/workOrder/statistics",
                redirect: "/workOrder/statistics/overview",
                sort: "999",
                meta: {
                    key: "statistics",
                    title: "统计",
                    icon: "",
                    isMenuShow: true,
                    isBlank: false,
                    isRegister: false,
                },
                layout: "default",
                children: [
                    {
                        id: "2-1-1",
                        name: "overview",
                        level: "3",
                        path: "/workOrder/statistics/overview",
                        sort: "999",
                        meta: {
                            key: "overview",
                            title: "概览",
                            icon: "",
                            isMenuShow: true,
                            isBlank: false,
                            isRegister: true,
                        },
                        layout: "default",
                        children: [],
                    },
                    {
                        id: "2-1-2",
                        name: "workload",
                        level: "3",
                        path: "/workOrder/statistics/workload",
                        sort: "999",
                        meta: {
                            key: "workload",
                            title: "客服工作量",
                            icon: "",
                            isMenuShow: true,
                            isBlank: false,
                            isRegister: true,
                        },
                        layout: "default",
                        children: [],
                    },
                ],
            },
            {
                id: "2-2",
                name: "searching",
                level: "2",
                path: "/workOrder/searching",
                redirect: "/workOrder/searching/customSearch",
                sort: "999",
                meta: {
                    key: "searching",
                    title: "工单查询",
                    icon: "",
                    isMenuShow: true,
                    isBlank: false,
                    isRegister: false,
                },
                layout: "default",
                children: [
                    {
                        id: "2-2-1",
                        name: "customSearch",
                        level: "2",
                        path: "/workOrder/searching/customSearch",
                        sort: "999",
                        meta: {
                            key: "customSearch",
                            title: "自定义查询",
                            icon: "",
                            isMenuShow: true,
                            isBlank: false,
                            isRegister: true,
                        },
                        layout: "default",
                        children: [],
                    },
                ],
            },
        ],
    },
    {
        id: "3",
        name: "CRM",
        level: "1",
        path: "/CRM",
        redirect: "/CRM/customer/firstConsultCustom",
        sort: "999",
        meta: {
            key: "CRM",
            title: "CRM",
            icon: "&#xe828;",
            isMenuShow: true,
            isBlank: false,
            isRegister: true,
        },
        layout: "default",
        children: [
            {
                id: "3-1",
                name: "customer",
                level: "2",
                path: "/CRM/customer",
                redirect: "/CRM/customer/firstConsultCustom",
                sort: "999",
                meta: {
                    key: "customer",
                    title: "客户中心",
                    icon: "",
                    isMenuShow: true,
                    isBlank: false,
                    isRegister: false,
                },
                layout: "default",
                children: [
                    {
                        id: "3-1-1",
                        name: "firstConsultCustom",
                        level: "3",
                        path: "/CRM/customer/firstConsultCustom",
                        sort: "999",
                        meta: {
                            key: "firstConsultCustom",
                            title: "首咨客户",
                            icon: "",
                            isMenuShow: true,
                            isBlank: false,
                            isRegister: true,
                        },
                        layout: "default",
                        children: [],
                    },
                    {
                        id: "3-1-2",
                        name: "toBeDistributedCustom",
                        level: "3",
                        path: "/CRM/customer/toBeDistributedCustom",
                        sort: "999",
                        meta: {
                            key: "toBeDistributedCustom",
                            title: "待分配客户",
                            icon: "",
                            isMenuShow: true,
                            isBlank: false,
                            isRegister: true,
                        },
                        layout: "default",
                        children: [],
                    },
                ],
            },
        ],
    },
    {
        id: "4",
        name: "management",
        level: "1",
        path: "/management",
        redirect: "/management/service/list",
        sort: "999",
        meta: {
            key: "management",
            title: "管理中心",
            icon: "&#xe844;",
            isMenuShow: true,
            isBlank: false,
            isRegister: true,
        },
        layout: "default",
        children: [
            {
                id: "4-1",
                name: "service",
                level: "2",
                path: "/management/service",
                redirect: "/management/service/list",
                sort: "999",
                meta: {
                    key: "service",
                    title: "客服管理",
                    icon: "",
                    isMenuShow: true,
                    isBlank: false,
                    isRegister: false,
                },
                layout: "default",
                children: [
                    {
                        id: "4-1-1",
                        name: "serviceList",
                        level: "3",
                        path: "/management/service/list",
                        sort: "999",
                        meta: {
                            key: "serviceList",
                            title: "客服列表",
                            icon: "",
                            isMenuShow: true,
                            isBlank: false,
                            isRegister: true,
                        },
                        layout: "default",
                        children: [],
                    },
                ],
            },
        ],
    },
];
